site_name: 'WSo2 API Manager 2.6.0'
repo_url: 'https://github.com/shaniR/product-apim/tree/product-scenarios'
edit_uri: product-scenarios
site_description: 'WSO2 API Manager'
site_author: 'WSO2, Inc.'
copyright: '2018 WSO2, Inc.'
docs_dir: abc
nav:
    - Introduction: '1Introduction/Introduction.md'
    - Quick Start Guide: '2QuickStartGuide/QuickStartGuide.md'
    - Key Concepts: '3KeyConcepts/KeyConcepts.md'
    - Capabilities : 
        - API Design:
            - REST API:
                - Create and Publish a REST API : '4Scenarios/4product-scenarios/1-manage-public-partner-private-apis/1.1-expose-service-as-rest-api/1.1.1-create-rest-api-from-scratch/'
                - Create and Publish an API from a Swagger Definition: '4Scenarios/4product-scenarios/1-manage-public-partner-private-apis/1.1-expose-service-as-rest-api/1.1.2-create-rest-api-by-import-oas-document/README.md'
            - SOAP API: ''
            - WEBSOCKET API: ''
            - API PROXY CREATION: ''
            - ENDPOINTS: ''
            - API Versioning: 
                - Create Default Version: ''
                - Create a New Version: ''
        - API Developer Portal: ''
        - API Gateway : ''
        - API Microgateway : ''
        - Rate Limiting : ''
        - API Security : ''
        - Analytics : ''
        - Administration : ''
        - Extentions : ''
        - Reference : ''
    - Business Scenarios : ''
    - Developer Guide: '5DeveloperGuide/DeveloperGuide.md'
    - Deployment Guide: '6DeploymentGuide/DeploymentGuide.md'
    - Admin Guide: '7AdminGuide/AdminGuide.md'
    - Reference : '8Reference/Reference.md'
    - Troubleshooting : '9Troubleshooting/Troubleshooting.md'
theme:
  name: material
